import { useAppStore } from "../stores/app.js";
import {
  createDataset,
  createSnapshot,
  createPool,
  destroyDataset,
  destroySnapshot,
  destroyPool,
  createTaskSchedule,
  deleteTaskSchedule,
  getTask,
  getTaskSchedules,
  getTasks,
  getSnapshot,
  getSnapshotFilters,
  getSnapshots,
  getDatasetSnapshots,
  getSettings,
  removePoolTarget,
  rollbackSnapshot,
  saveSettings,
  startPoolScrub,
  stopPoolScrub,
  testSshConnection,
  updateDatasetProperties,
  updatePoolProperties,
  updateTaskSchedule,
  updatePoolTopology,
} from "../services/api.js";

export function useAppState() {
  const appStore = useAppStore();

  return {
    state: appStore.state,
    connect: appStore.connect,
    createDataset,
    createSnapshot,
    destroyDataset,
    destroySnapshot,
    disconnect: appStore.disconnect,
    forceRefreshState: appStore.forceRefreshState,
    createTaskSchedule,
    deleteTaskSchedule,
    getTask,
    getTaskSchedules,
    getTasks,
    getSnapshot,
    getSnapshotFilters,
    getSnapshots,
    getDatasetSnapshots,
    getSettings,
    login: appStore.login,
    createPool,
    destroyPool,
    logout: appStore.logout,
    removePoolTarget,
    rollbackSnapshot,
    refreshAuthStatus: appStore.refreshAuthStatus,
    refreshStateOnce: appStore.refreshStateOnce,
    saveSettings,
    startPoolScrub,
    stopPoolScrub,
    testSshConnection,
    updateDatasetProperties,
    updatePoolProperties,
    updateTaskSchedule,
    updatePoolTopology,
  };
}
