from __future__ import annotations

# Keep REST-layer capability rules close to the API boundary so validation can
# reject unsupported edits before we ever open an SSH write workflow.
DATASET_EDITABLE_PROPERTIES = {
    "filesystem": {
        "aclinherit",
        "aclmode",
        "acltype",
        "atime",
        "canmount",
        "checksum",
        "compression",
        "copies",
        "dedup",
        "devices",
        "dnodesize",
        "exec",
        "logbias",
        "mountpoint",
        "nbmand",
        "overlay",
        "primarycache",
        "quota",
        "readonly",
        "recordsize",
        "redundant_metadata",
        "refquota",
        "refreservation",
        "relatime",
        "reservation",
        "secondarycache",
        "setuid",
        "snapdir",
        "sync",
        "xattr",
    },
    "volume": {
        "checksum",
        "compression",
        "copies",
        "dedup",
        "logbias",
        "primarycache",
        "readonly",
        "refreservation",
        "reservation",
        "secondarycache",
        "snapdev",
        "sync",
        "volmode",
        "volsize",
    },
    "snapshot": set(),
}

DATASET_CREATE_ALLOWED_PROPERTIES = {
    "filesystem": {
        "aclinherit",
        "aclmode",
        "acltype",
        "atime",
        "canmount",
        "casesensitivity",
        "checksum",
        "compression",
        "copies",
        "dedup",
        "devices",
        "dnodesize",
        "exec",
        "logbias",
        "mountpoint",
        "nbmand",
        "normalization",
        "overlay",
        "primarycache",
        "quota",
        "readonly",
        "recordsize",
        "redundant_metadata",
        "refquota",
        "refreservation",
        "relatime",
        "reservation",
        "secondarycache",
        "setuid",
        "snapdir",
        "sync",
        "utf8only",
        "xattr",
    },
    "volume": {
        "checksum",
        "compression",
        "copies",
        "dedup",
        "logbias",
        "primarycache",
        "readonly",
        "refreservation",
        "reservation",
        "secondarycache",
        "snapdev",
        "sync",
        "volblocksize",
        "volmode",
        "volsize",
    },
}
